/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicY7ResultRouteImport } from './routes/api/public/y7-result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicY7ResultRoute = ApiPublicY7ResultRouteImport.update({
  id: '/api/public/y7-result',
  path: '/api/public/y7-result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/y7-result': typeof ApiPublicY7ResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/y7-result': typeof ApiPublicY7ResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/y7-result': typeof ApiPublicY7ResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/y7-result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/y7-result'
  id: '__root__' | '/' | '/api/public/y7-result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicY7ResultRoute: typeof ApiPublicY7ResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/y7-result': {
      id: '/api/public/y7-result'
      path: '/api/public/y7-result'
      fullPath: '/api/public/y7-result'
      preLoaderRoute: typeof ApiPublicY7ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicY7ResultRoute: ApiPublicY7ResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
